name: Primeira Pipeline

on:
  push:
    branches: [main]
jobs:
  teste_div:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar Código do Repositório
      uses: actions/checkout@v4
    
    - name: Configurar node
      uses: actions/setup-node@v7

    - run: "node test_sum"

  deploy:
    needs: [teste_soma]
    runs-on: ubuntu-latest
    steps:
     - run: echo "Deploy realizado"

